/**
 * src/router.tsx
 *
 * TanStack Router factory — creates a fully-configured router instance.
 * Called by both entry-client.tsx (hydration) and entry-server.tsx (SSR).
 *
 * The routeTree is generated by the TanStack Router CLI / plugin from
 * src/routes/**  and written to src/routeTree.gen.ts.
 */

import { createRouter as createTanStackRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

export function createRouter() {
  return createTanStackRouter({
    routeTree,
    defaultPreload: 'intent',
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}

// Ensure compatibility with internal plugin expectations
export const getRouter = createRouter;
